// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks_usecase

import (
	context "context"

	model "github.com/brunobrolesi/open-garden-core/internal/farm/business/model"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/brunobrolesi/open-garden-core/internal/farm/business/usecase"
)

// GetUserFarmUseCase is an autogenerated mock type for the GetUserFarmUseCase type
type GetUserFarmUseCase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, input
func (_m *GetUserFarmUseCase) Exec(ctx context.Context, input usecase.GetUserFarmInputDto) (model.Farm, error) {
	ret := _m.Called(ctx, input)

	var r0 model.Farm
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetUserFarmInputDto) model.Farm); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.Farm)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetUserFarmInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGetUserFarmUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetUserFarmUseCase creates a new instance of GetUserFarmUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetUserFarmUseCase(t mockConstructorTestingTNewGetUserFarmUseCase) *GetUserFarmUseCase {
	mock := &GetUserFarmUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
