version: '3'

services:
  postgres-db:
    image: postgres:15.4
    container_name: postgres-db
    restart: always
    tty: true
    volumes:
      - ./db/postgres-dump:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    ports:
      - 5433:5432

  timescale-db:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale-db
    restart: always
    tty: true
    volumes:
      - ./db/timescale-dump:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    ports:
      - 5434:5432

  app:
    build: 
      context: .
    container_name: app
    entrypoint: wait-for postgres-db:5432 -t 30 -- wait-for timescale-db:5432 -t 30 -- ./open_garden_core 
    networks:
      - backend
      - frontend
    tty: true
    depends_on:
      - postgres-db
      - timescale-db

  nginx:
    build: 
      context: nginx
    environment:
      - APP_PORT=${APP_PORT}
    container_name: nginx
    networks:
      - frontend
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge