// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks_usecase

import (
	context "context"

	model "github.com/brunobrolesi/open-garden-core/internal/sensor/business/model"
	usecase "github.com/brunobrolesi/open-garden-core/internal/sensor/business/usecase"
	mock "github.com/stretchr/testify/mock"
)

// AddFarmSensorUseCase is an autogenerated mock type for the AddFarmSensorUseCase type
type AddFarmSensorUseCase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, farm
func (_m *AddFarmSensorUseCase) Exec(ctx context.Context, farm usecase.AddFarmSensorInputDto) (model.FarmSensor, error) {
	ret := _m.Called(ctx, farm)

	var r0 model.FarmSensor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AddFarmSensorInputDto) (model.FarmSensor, error)); ok {
		return rf(ctx, farm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.AddFarmSensorInputDto) model.FarmSensor); ok {
		r0 = rf(ctx, farm)
	} else {
		r0 = ret.Get(0).(model.FarmSensor)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.AddFarmSensorInputDto) error); ok {
		r1 = rf(ctx, farm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAddFarmSensorUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddFarmSensorUseCase creates a new instance of AddFarmSensorUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddFarmSensorUseCase(t mockConstructorTestingTNewAddFarmSensorUseCase) *AddFarmSensorUseCase {
	mock := &AddFarmSensorUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
