// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks_usecase

import (
	context "context"

	model "github.com/brunobrolesi/open-garden-core/internal/sensor/business/model"
	usecase "github.com/brunobrolesi/open-garden-core/internal/sensor/business/usecase"
	mock "github.com/stretchr/testify/mock"
)

// GetFarmSensorsUseCase is an autogenerated mock type for the GetFarmSensorsUseCase type
type GetFarmSensorsUseCase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, input
func (_m *GetFarmSensorsUseCase) Exec(ctx context.Context, input usecase.GetFarmSensorsInputDto) (model.FarmSensors, error) {
	ret := _m.Called(ctx, input)

	var r0 model.FarmSensors
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetFarmSensorsInputDto) (model.FarmSensors, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetFarmSensorsInputDto) model.FarmSensors); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FarmSensors)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetFarmSensorsInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetFarmSensorsUseCase creates a new instance of GetFarmSensorsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetFarmSensorsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetFarmSensorsUseCase {
	mock := &GetFarmSensorsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
