// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks_gateway

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/brunobrolesi/open-garden-core/internal/sensor/business/model"
)

// FarmService is an autogenerated mock type for the FarmService type
type FarmService struct {
	mock.Mock
}

// GetFarmByIdAndUserId provides a mock function with given fields: ctx, farmID, userID
func (_m *FarmService) GetFarmByIdAndUserId(ctx context.Context, farmID int, userID int) (model.Farm, error) {
	ret := _m.Called(ctx, farmID, userID)

	var r0 model.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (model.Farm, error)); ok {
		return rf(ctx, farmID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) model.Farm); ok {
		r0 = rf(ctx, farmID, userID)
	} else {
		r0 = ret.Get(0).(model.Farm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, farmID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFarmService creates a new instance of FarmService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFarmService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FarmService {
	mock := &FarmService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
