// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks_gateway

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/brunobrolesi/open-garden-core/internal/sensor/business/model"
)

// SensorRepository is an autogenerated mock type for the SensorRepository type
type SensorRepository struct {
	mock.Mock
}

// GetSensorById provides a mock function with given fields: ctx, id
func (_m *SensorRepository) GetSensorById(ctx context.Context, id int) (model.Sensor, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Sensor
	if rf, ok := ret.Get(0).(func(context.Context, int) model.Sensor); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Sensor)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSensorRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSensorRepository creates a new instance of SensorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSensorRepository(t mockConstructorTestingTNewSensorRepository) *SensorRepository {
	mock := &SensorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
